/*
 * rdp-retina – Einstellungen der Oberfläche: Server, RemoteApps, Übertragung, Arbeitsbereich
 *
 * Gespeichert in den NSUserDefaults der App (in der App Sandbox liegen sie im Container),
 * Kennwörter im Schlüsselbund (RRCredentials), hochgeladene Symbole als PNG unter
 * Application Support. Die Modellobjekte sind Kopien: bearbeiten, dann mit save… übernehmen.
 * Jede Änderung meldet RRConfigDidChangeNotification. Nur im Hauptthread.
 */
#import <AppKit/AppKit.h>

NS_ASSUME_NONNULL_BEGIN

extern NSNotificationName const RRConfigDidChangeNotification;

@interface RRServerConfig : NSObject <NSCopying>

+ (instancetype)newServer; /* mit neuer ID, sonst leer */

@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *name;     /* leer = Adresse */
@property (nonatomic, copy) NSString *host;     /* Name oder IP, ohne Port */
@property (nonatomic) NSUInteger port;          /* 0 = 3389 */
@property (nonatomic, copy) NSString *username; /* ohne Domäne */
@property (nonatomic, copy) NSString *domain;   /* leer = keine */

@property (nonatomic, readonly) NSString *displayName;
/* Eingabe "host:port" bzw. "DOMÄNE\benutzer" in die Felder zerlegen. */
- (void)setAddress:(NSString *)address;
- (void)setAccount:(NSString *)account;
/* Ohne Adresse lässt sich nicht verbinden. */
@property (nonatomic, readonly, getter=isComplete) BOOL complete;

@end

@interface RRAppConfig : NSObject <NSCopying>

+ (instancetype)newApp; /* mit neuer ID, sonst leer */

@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *serverId;
@property (nonatomic, copy) NSString *program;     /* "||notepad" oder "C:\Windows\System32\notepad.exe" */
@property (nonatomic, copy) NSString *arguments;   /* leer = keine */
@property (nonatomic, copy) NSString *processName; /* leer = aus program abgeleitet; auch eine App-ID */
/* Gelernte App-IDs (MS-RDPERP Get Application ID) von Fenstern, die nach einem Start dieser
 * RemoteApp erschienen – für Programme ohne .exe in der ID, z.B. den Task-Manager. */
@property (nonatomic, copy) NSArray<NSString *> *knownApplicationIds;

/* Dateiname der .exe für die Zuordnung von Fenstern, klein ("notepad.exe"); "" = unbekannt */
@property (nonatomic, readonly) NSString *matchProcessName;
/* Gehört ein Fenster mit dieser App-ID zu dieser RemoteApp? Windows meldet z.B.
 * "{1AC14E77-…}\notepad.exe" oder "Microsoft.AutoGenerated.{923DD477-…}". */
- (BOOL)matchesApplicationId:(NSString *)applicationId;
/* Angabe für rr_rail_launch: "program:…[,cmd:…]" */
@property (nonatomic, readonly) NSString *launchSpec;
@property (nonatomic, readonly, getter=isComplete) BOOL complete;

@end

typedef NS_ENUM(NSInteger, RRSoundMode) {
	RRSoundModeMac = 0,    /* /audio-mode:0 */
	RRSoundModeServer = 1, /* /audio-mode:1 */
	RRSoundModeOff = 2,    /* /audio-mode:2 */
};

@interface RRTransferConfig : NSObject <NSCopying>
@property (nonatomic) NSInteger maxApps;           /* gleichzeitig offene RemoteApps, 0 = unbegrenzt */
@property (nonatomic) BOOL autoReconnect;          /* Vorgabe YES */
@property (nonatomic) NSInteger reconnectAttempts; /* 1…1000, Vorgabe 20 */
@property (nonatomic) RRSoundMode sound;           /* Vorgabe Mac */
@property (nonatomic) BOOL microphone;             /* Vorgabe NO */
@property (nonatomic) BOOL clipboard;              /* Vorgabe YES */
@property (nonatomic) BOOL multimon;               /* alle Bildschirme, Vorgabe NO */
@property (nonatomic) NSInteger scalePercent;      /* 0 = wie der Bildschirm, sonst 100…500 */
@end

/* Ein Fenster im gespeicherten Arbeitsbereich */
@interface RRWorkspaceItem : NSObject <NSCopying>
@property (nonatomic, copy) NSString *appId;
@property (nonatomic) NSRect serverRect; /* Server-Pixel wie rrWindow.rect, y wächst nach unten */
@property (nonatomic) BOOL minimized;
@property (nonatomic) BOOL maximized;
@end

@interface RRWorkspaceConfig : NSObject <NSCopying>
@property (nonatomic) BOOL saveOnQuit;      /* Vorgabe YES */
@property (nonatomic) BOOL restoreFromLink; /* beim Öffnen einer Verknüpfung, Vorgabe YES */
@property (nonatomic, copy, nullable) NSDate *savedAt;
@property (nonatomic, copy) NSArray<RRWorkspaceItem *> *items;
@end

@interface RRConfig : NSObject

+ (RRConfig *)shared;

@property (nonatomic, readonly) NSArray<RRServerConfig *> *servers; /* Kopien, Reihenfolge der Anlage */
@property (nonatomic, readonly) NSArray<RRAppConfig *> *apps;       /* Kopien, nach Name */
@property (nonatomic, readonly) RRTransferConfig *transfer;         /* Kopie */
@property (nonatomic, readonly) RRWorkspaceConfig *workspace;       /* Kopie */

- (nullable RRServerConfig *)serverWithId:(NSString *)identifier;
- (nullable RRAppConfig *)appWithId:(NSString *)identifier;
- (NSArray<RRAppConfig *> *)appsForServerId:(NSString *)identifier;

- (void)saveServer:(RRServerConfig *)server;       /* neu oder ersetzen */
- (void)removeServerWithId:(NSString *)identifier; /* samt RemoteApps und Kennwort */
- (void)saveApp:(RRAppConfig *)app;
- (void)removeAppWithId:(NSString *)identifier;     /* samt Symbol */
- (void)saveTransfer:(RRTransferConfig *)transfer;
- (void)saveWorkspace:(RRWorkspaceConfig *)workspace;

/* Kennwort im Schlüsselbund, nil = keins gespeichert */
- (nullable NSString *)passwordForServer:(RRServerConfig *)server;
/* nil oder "" löscht */
- (BOOL)setPassword:(nullable NSString *)password
          forServer:(RRServerConfig *)server
              error:(NSError *_Nullable *_Nullable)error;

/* Hochgeladenes Symbol (quadratisch aufbereitet), nil = keins */
- (nullable NSImage *)iconForAppId:(NSString *)identifier;
/* nil löscht */
- (BOOL)setIcon:(nullable NSImage *)image
       forAppId:(NSString *)identifier
          error:(NSError *_Nullable *_Nullable)error;

/* Kommandozeile für die Sitzung zu server: RemoteApp ohne erstes Programm
 * (/retina-remoteapp) und die Übertragungseinstellungen. argv[0] ist "rdp-retina", ein Kennwort
 * steht nicht darin (RRSession holt es aus dem Schlüsselbund). */
- (NSArray<NSString *> *)sessionArgumentsForServer:(RRServerConfig *)server;

@end

NS_ASSUME_NONNULL_END
